package presentation.userUI.Operator;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;

public class OperatorLeftSelectUIController {
	@FXML
	private Button homeButton;
	@FXML
	private Button userButton;
	@FXML
	private Label homeBackground;
	@FXML
	private Label userBackground;

	public void init(){
		homeButton.setTooltip(new Tooltip("个人信息"));
		userButton.setTooltip(new Tooltip("用户管理"));
	}

	public void setUserBackground(){
		userBackground.setVisible(true);
	}

	public void setHomeBackground(){
		homeBackground.setVisible(true);
	}

	// Event Listener on Button[#homeButton].onMouseClicked
	@FXML
	public void toHomePane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		OperatorUIController operatorController = OperatorUIController.getOperatorUIController();
		operatorController.runNewStage("homeButton");
	}
	// Event Listener on Button[#customerButton].onMouseClicked
	@FXML
	public void toUserPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		OperatorUIController operatorController = OperatorUIController.getOperatorUIController();
		operatorController.runNewStage("userButton");
	}

}
