package presentation.mainUI;

import javafx.fxml.FXML;

import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import presentation.messageUI.MessageMainUI;

public class ControBarController {
	@FXML
	private Label closeBackground;
	@FXML
	private Label close;
	@FXML
	private Label messageBackground;
	@FXML
	private Label message;
	@FXML
	private Label logoutBackground;
	@FXML
	private Label logout;

	//增加进出反馈
	// Event Listener on Label[#closeBackground].onMouseEntered
	@FXML
	public void setCloseVisable(MouseEvent event) {
		// TODO Autogenerated
		closeBackground.setOpacity(0.71);
	}
	// Event Listener on Label[#closeBackground].onMouseExited
	@FXML
	public void setCloseUnvisable(MouseEvent event) {
		// TODO Autogenerated
		closeBackground.setOpacity(0.01);
	}

	//关闭界面
	// Event Listener on Label[#closeLabel].onMouseClicked
	@FXML
	public void closeStage(MouseEvent event) {
		// TODO Autogenerated
		UIController.getUIController().exit();
	}
	//增加进出反馈
	// Event Listener on Label[#messageBackground].onMouseEntered
	@FXML
	public void setMessageVisable(MouseEvent event) {
		// TODO Autogenerated
		messageBackground.setOpacity(0.71);
	}
	// Event Listener on Label[#messageBackground].onMouseExited
	@FXML
	public void setMessageUnvisable(MouseEvent event) {
		// TODO Autogenerated
		messageBackground.setOpacity(0.01);
	}

	//打开消息界面
	// Event Listener on Label[#messageBackground].onMouseExited
	@FXML
	public void toMessagePane(MouseEvent event) throws Exception {
		// TODO Autogenerated
		MessageMainUI message = new MessageMainUI();
		System.out.println("uicontroller的user:"+UIController.getUIController().defaultuser);
		message.user=UIController.getUIController().defaultuser;
		message.start(new Stage());
	}
	//增加进出反馈
	// Event Listener on Label[#logoutBackground1].onMouseEntered
	@FXML
	public void setLogoutVisable(MouseEvent event) {
		// TODO Autogenerated
		logoutBackground.setOpacity(0.71);
	}
	// Event Listener on Label[#logoutBackground1].onMouseExited
	@FXML
	public void setLogoutUnvisable(MouseEvent event) {
		// TODO Autogenerated
		logoutBackground.setOpacity(0.01);
	}

	//登出
	// Event Listener on Label[#closeLabel].onMouseClicked
	@FXML
	public void logout(MouseEvent event) throws Exception {
		// TODO Autogenerated
		UIController.getUIController().logout();

	}

	void init(){
		logoutBackground.setTooltip(new Tooltip("账号登出"));
		messageBackground.setTooltip(new Tooltip("提示消息"));
		closeBackground.setTooltip(new Tooltip("退出系统"));
		logout.setTooltip(new Tooltip("账号登出"));
		message.setTooltip(new Tooltip("提示消息"));
		close.setTooltip(new Tooltip("退出系统"));
	}

}
