package presentation.customerUI;

import java.io.IOException;
import java.util.ArrayList;

import BL.customerBL.CustomerController;
import BLService.customerBLService.CustomerBLService;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import po.KeyForSearchCustomer;
import presentation.littleUI.QiPaoUI;
import presentation.mainUI.UIController;
import presentation.userUI.SaleManager.SaleUIController;
import vo.CustomerVO;

public class CustomerMainUIController {
	@FXML
	private Button backButton;
	@FXML
	private Button selectButton;
	@FXML
	private TextField sereach;
	@FXML
	private Button deleteButton;
	@FXML
	private Button newButton;
	@FXML
	private ScrollPane listPane;

	public void setDeleteButton() {
		// TODO Autogenerated
		deleteButton.setVisible(true);
	}
	public void removeDeleteButton() {
		// TODO Autogenerated
		deleteButton.setVisible(false);
	}
	// Event Listener on Button[#deleteButton].onMouseClicked
	@FXML
	public void deleteCustomer(MouseEvent event) {
		// TODO Autogenerated
	}
	 //Event Listener on Button[#deleteButton].onMouseEntered
	@FXML
	public void enterDeleteButton(MouseEvent event) {
		// TODO Autogenerateds
		deleteButton.setLayoutX(deleteButton.getLayoutX()+1);
		deleteButton.setLayoutY(deleteButton.getLayoutY()+1);
	}
	// Event Listener on Button[#deleteButton].onMouseExited
	@FXML
	public void exitDeleteButton(MouseEvent event) {
		// TODO Autogenerated
		deleteButton.setLayoutX(deleteButton.getLayoutX()-1);
		deleteButton.setLayoutY(deleteButton.getLayoutY()-1);
	}


	public void setSelectButton() {
		// TODO Autogenerated
		selectButton.setVisible(true);
	}
	public void removeSelectButton() {
		// TODO Autogenerated
		selectButton.setVisible(false);
	}
	// Event Listener on Button[#selectButton].onMouseClicked 搜索关键字
	@FXML
	public void selectCustomer(MouseEvent event) throws IOException {
		// TODO Autogenerated
		KeyForSearchCustomer key= new KeyForSearchCustomer();
		key.setName(sereach.getText());

		CustomerBLService customerBLService = new CustomerController();
		ArrayList<CustomerVO> customerList=customerBLService.getCustomerList(key);

		SaleUIController.getSaleUIController().setKey(key);
		SaleUIController.getSaleUIController().setMode("sel");
		SaleUIController.getSaleUIController().runNewStage("customerButton");

		QiPaoUI notice = new QiPaoUI();
		notice.showTip((Pane)UIController.getUIController().getUIStage().getScene().getRoot(), "搜索到"+customerList.size()+"个相关客户");

	}
	// Event Listener on Button[#selectButton].onMouseExited
	@FXML
	public void enterSelectButton(MouseEvent event) {
		// TODO Autogenerated
		selectButton.setLayoutX(selectButton.getLayoutX()+1);
		selectButton.setLayoutY(selectButton.getLayoutY()+1);
	}
	// Event Listener on Button[#selectButton].onMouseExited
	@FXML
	public void exitSelectButton(MouseEvent event) {
		// TODO Autogenerated
		selectButton.setLayoutX(selectButton.getLayoutX()-1);
		selectButton.setLayoutY(selectButton.getLayoutY()-1);
	}


	public void setNewButton() {
		// TODO Autogenerated
		newButton.setVisible(true);
	}
	public void removeNewButton() {
		// TODO Autogenerated
		newButton.setVisible(false);
	}
	// Event Listener on Button[#newButton].onMouseClicked
	@FXML
	public void newCustomer(MouseEvent event) throws Exception {
		// TODO Autogenerated
		NewCustomerUI newcustomer =  new NewCustomerUI();
		newcustomer.start(new Stage());
	}
	// Event Listener on Button[#newButton].onMouseEntered
	@FXML
	public void enterNewButton(MouseEvent event) {
		// TODO Autogenerated
		newButton.setLayoutX(newButton.getLayoutX()+1);
		newButton.setLayoutY(newButton.getLayoutY()+1);
	}
	// Event Listener on Button[#newButton].onMouseExited
	@FXML
	public void exitNewButton(MouseEvent event) {
		// TODO Autogenerated
		newButton.setLayoutX(newButton.getLayoutX()-1);
		newButton.setLayoutY(newButton.getLayoutY()-1);
	}
	public void setScrollPane(VBox list) {
		// TODO Auto-generated method stub
		listPane.setStyle("-fx-border:transparent;");
		listPane.setContent(list);
	}

	public void setBackButton() {
		// TODO Autogenerated
		backButton.setVisible(true);
	}
	public void removeBackButton() {
		// TODO Autogenerated
		backButton.setVisible(false);
	}
	// Event Listener on Button[#selectButton].onMouseClicked 返回
	@FXML
	public void goBack(MouseEvent event) throws IOException {
		// TODO Autogenerated
		KeyForSearchCustomer key= new KeyForSearchCustomer();
		SaleUIController.getSaleUIController().setKey(key);
		SaleUIController.getSaleUIController().setMode("new");
		SaleUIController.getSaleUIController().runNewStage("customerButton");
	}
}
