package presentation.userUI.StoreManager;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;

public class StoreLeftSelectUIController {
	@FXML
	private Button homeButton;
	@FXML
	private Button receiptButton;
	@FXML
	private Button goodButton;
	@FXML
	private Button stockButton;
	@FXML
	private Button stockprocessButton;
	@FXML
	private Label homeBackground;
	@FXML
	private Label receiptBackground;
	@FXML
	private Label goodBackground;
	@FXML
	private Label stockBackground;
	@FXML
	private Label stockprocessBackground;

	public void init(){
		homeButton.setTooltip(new Tooltip("个人信息"));
		receiptButton.setTooltip(new Tooltip("单据界面"));
		goodButton.setTooltip(new Tooltip("商品管理界面"));
		stockButton.setTooltip(new Tooltip("库存快照界面"));
		stockprocessButton.setTooltip(new Tooltip("库存查看界面"));
	}

	public void setGoodBackground(){
		goodBackground.setVisible(true);
	}

	public void setHomeBackground(){
		homeBackground.setVisible(true);
	}

	public void setReceiptBackground(){
		receiptBackground.setVisible(true);
	}

	public void setStockBackground(){
		stockBackground.setVisible(true);
	}

	public void setStockprocessBackground(){
		stockprocessBackground.setVisible(true);
	}

	// Event Listener on Button[#homeButton].onMouseClicked
	@FXML
	public void toHomePane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		StoreUIController storeController = StoreUIController.getStoreUIController();
		storeController.runNewStage("homeButton",null);
	}
	// Event Listener on Button[#customerButton].onMouseClicked
	@FXML
	public void toGoodPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		StoreUIController storeController = StoreUIController.getStoreUIController();
		storeController.runNewStage("goodButton",null);
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toRecieptPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		StoreUIController storeController = StoreUIController.getStoreUIController();
		storeController.runNewStage("receiptButton",null);
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toStockPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		StoreUIController storeController = StoreUIController.getStoreUIController();
		storeController.runNewStage("stockButton",null);
	}
	@FXML
	public void toStockprocessPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		StoreUIController storeController = StoreUIController.getStoreUIController();
		storeController.runNewStage("stockprocessButton",null);
	}
}
