package presentation.userUI.GeneralManager;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;
import vo.UserVO;

public class GeneralLeftSelectUIController {
	@FXML
	private Button homeButton;
	@FXML
	private Button receiptButton;
	@FXML
	private Button reportButton;
	@FXML
	private Button strategyButton;
	@FXML
	private Button accountButton;
	@FXML
	private Button systemlogButton;
	@FXML
	private Label receiptBackground;
	@FXML
	private Label homeBackground;
	@FXML
	private Label reportBackground;
	@FXML
	private Label strategyBackground;
	@FXML
	private Label systemlogBackground;

	public void init(){
		homeButton.setTooltip(new Tooltip("个人信息"));
		reportButton.setTooltip(new Tooltip("报表管理"));
		receiptButton.setTooltip(new Tooltip("单据界面"));
		strategyButton.setTooltip(new Tooltip("促销策略界面"));
		systemlogButton.setTooltip(new Tooltip("系统操作日志"));
	}

	public void setReportBackground(){
		reportBackground.setVisible(true);
	}

	public void setHomeBackground(){
		homeBackground.setVisible(true);
	}

	public void setReceiptBackground(){
		receiptBackground.setVisible(true);
	}

	public void setStrategyBackground(){
		strategyBackground.setVisible(true);
	}

	public void setSystemlogBackground(){
		systemlogBackground.setVisible(true);
	}

	// Event Listener on Button[#homeButton].onMouseClicked
	@FXML
	public void toHomePane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		GeneralUIController generalController = GeneralUIController.getGeneralUIController();
		generalController.runNewStage("homeButton");
	}
	// Event Listener on Button[#customerButton].onMouseClicked
	@FXML
	public void toReportPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		GeneralUIController generalController = GeneralUIController.getGeneralUIController();
		generalController.runNewStage("reportButton");
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toRecieptPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		GeneralUIController generalController = GeneralUIController.getGeneralUIController();
		generalController.runNewStage("receiptButton");
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toStrategyPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		GeneralUIController generalController = GeneralUIController.getGeneralUIController();
		generalController.runNewStage("strategyButton");
	}
	@FXML
	public void toSystemlogPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		GeneralUIController generalController = GeneralUIController.getGeneralUIController();
		generalController.runNewStage("systemlogButton");
	}
}
