package presentation.userUI.FinancialManager;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;

public class FinancialLeftSelectUIController {
	@FXML
	private Button homeButton;
	@FXML
	private Button receiptButton;
	@FXML
	private Button reportButton;
	@FXML
	private Button bankButton;
	@FXML
	private Button accountButton;
	@FXML
	private Button systemlogButton;
	@FXML
	private Label receiptBackground;
	@FXML
	private Label homeBackground;
	@FXML
	private Label reportBackground;
	@FXML
	private Label bankBackground;
	@FXML
	private Label accountBackground;
	@FXML
	private Label systemlogBackground;

	public void init(){
		homeButton.setTooltip(new Tooltip("个人信息"));
		reportButton.setTooltip(new Tooltip("报表管理"));
		receiptButton.setTooltip(new Tooltip("单据界面"));
		bankButton.setTooltip(new Tooltip("银行账户界面"));
		accountButton.setTooltip(new Tooltip("建账界面"));
		systemlogButton.setTooltip(new Tooltip("系统操作日志"));
	}

	public void setReportBackground(){
		reportBackground.setVisible(true);
	}

	public void setHomeBackground(){
		homeBackground.setVisible(true);
	}

	public void setReceiptBackground(){
		receiptBackground.setVisible(true);
	}

	public void setAccountBackground(){
		accountBackground.setVisible(true);
	}

	public void setBankBackground(){
		bankBackground.setVisible(true);
	}

	public void setSystemlogBackground(){
		systemlogBackground.setVisible(true);
	}

	// Event Listener on Button[#homeButton].onMouseClicked
	@FXML
	public void toHomePane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FinancialUIController controller = FinancialUIController.getFinancialUIController();
		controller.runNewStage("homeButton",null);
	}
	// Event Listener on Button[#customerButton].onMouseClicked
	@FXML
	public void toReportPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FinancialUIController controller = FinancialUIController.getFinancialUIController();
		controller.runNewStage("reportButton",null);
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toRecieptPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FinancialUIController controller = FinancialUIController.getFinancialUIController();
		controller.runNewStage("receiptButton",null);
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toAccountPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FinancialUIController controller = FinancialUIController.getFinancialUIController();
		controller.runNewStage("createButton",null);
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toBankPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FinancialUIController controller = FinancialUIController.getFinancialUIController();
		controller.runNewStage("bankButton",null);
	}
	@FXML
	public void toSystemlogPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FinancialUIController controller = FinancialUIController.getFinancialUIController();
		controller.runNewStage("systemlogButton",null);
	}
}
