package presentation.operatorUI;

import java.io.File;
import java.io.IOException;
import java.rmi.RemoteException;

import BL.userBL.UserController;
import BLService.userBLService.UserBLServiceForAdmin;
import javafx.collections.FXCollections;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Tooltip;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import presentation.littleUI.QiPaoUI;
import presentation.mainUI.UIController;
import presentation.mainUI.UIcaller;
import presentation.userUI.Operator.OperatorUIController;
import utility.ImageZipUtil;
import utility.RoleOfUser;
import vo.UserVO;
import javafx.scene.control.ChoiceBox;

public class EditUserUIController {
	@FXML
	private AnchorPane Apane;
	@FXML
	private Label closeButtonBackground;
	@FXML
	private Label closeButton;
	@FXML
	private ImageView Img;
	@FXML
	private Label addPhotoLabel;
	@FXML
	private TextField userName;
	@FXML
	private ChoiceBox role;
	@FXML
	private TextField id;
	@FXML
	private TextField passwordcode;
	@FXML
	private Button confirmButton;
	@FXML
	private Button cancelButton;
	@FXML
	private Button deleteButton;

	private UserVO user = new UserVO();

	// 初始化
	public void init(UserVO uservo) throws RemoteException {
		this.user = uservo;
		id.setText(user.getID());
		passwordcode.setText(user.getPassword());
		userName.setText(user.getName());

		role.setItems(FXCollections.observableArrayList(RoleOfUser.FinancialManager, RoleOfUser.GeneralManager,
				RoleOfUser.SaleManager, RoleOfUser.saler, RoleOfUser.StoreManager));
		role.setTooltip(new Tooltip("选择用户职务"));
		role.getSelectionModel().select(user.getRole());
	}

	// 增添照片
	// Event Listener on Label[#addPhotoButton].onMouseClicked
	@FXML
	public void addPhoto(MouseEvent event) {
		// TODO Autogenerated

		addPhotoLabel.setTextFill(Color.PURPLE);

		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("Open Resource File");
		File file;

		file = fileChooser.showOpenDialog(new Stage());

		String filePath = "null";
		if (file == null) {
			return;
		}
		filePath = file.getAbsolutePath();

		if (filePath!=null) {
			String imgPath = "C://temp//" + filePath.hashCode() + ".png";
			ImageZipUtil.zipWidthHeightImageFile(new File(filePath), new File(imgPath), 80, 80, 1.0f);

			Image imagePush = new Image("file:" + imgPath);
			Img.setImage(imagePush);
			//System.out.println("pres"+imgPath);
			user.setImagePath(imgPath);

		}
	}

	private boolean judgenull() {
		// TODO Auto-generated method stub
		if (id.getText().equals("") || userName.getText().equals("")
				|| role.getSelectionModel().getSelectedItem() == null || passwordcode.getText().equals(""))
			return true;
		return false;
	}

	// 上傳用戶信息
	// Event Listener on Button[#confirmButton].onMouseClicked
	@FXML
	public void uploadCustomerInfo(MouseEvent event) throws IOException {
		// TODO Autogenerated
		if (judgenull()) {
			QiPaoUI notice = new QiPaoUI();
			notice.showTip(Apane, "用户核心信息不能为空！");
		} else {

			user.setName(userName.getText());
			user.setID(id.getText());
			user.setPassword(passwordcode.getText());
			String work = role.getSelectionModel().getSelectedItem().toString();
			if (work.equals(RoleOfUser.FinancialManager.toString()))
				user.setRole(RoleOfUser.FinancialManager);
			if (work.equals(RoleOfUser.GeneralManager.toString()))
				user.setRole(RoleOfUser.GeneralManager);
			if (work.equals(RoleOfUser.SaleManager.toString()))
				user.setRole(RoleOfUser.SaleManager);
			if (work.equals(RoleOfUser.saler.toString()))
				user.setRole(RoleOfUser.saler);
			if (work.equals(RoleOfUser.StoreManager.toString()))
				user.setRole(RoleOfUser.StoreManager);

			UserBLServiceForAdmin userBlService = new UserController();
			userBlService.updateUser(user);

			EditUserUI.getStage().close();
			OperatorUIController.getOperatorUIController().runNewStage("userButton");

			QiPaoUI notice = new QiPaoUI();
			notice.showTip((Pane) UIController.getUIController().getUIStage().getScene().getRoot(), "修改成功！");
		}
	}

	// Event Listener on Button[#cancelButton].onMouseClicked
	@FXML
	public void closeStage(MouseEvent event) {
		// TODO Autogenerated
		EditUserUI.getStage().close();
	}

	// 删除客户
	// Event Listener on Button[#cleearButton].onMouseClicked
	@FXML
	public void deleteUser(MouseEvent event) throws IOException {
		// TODO Autogenerated
		UserBLServiceForAdmin userBlService = new UserController();

		userBlService.deleteUser(user.getID());

		EditUserUI.thisStage.hide();
		OperatorUIController.getOperatorUIController().runNewStage("userButton");

		QiPaoUI notice = new QiPaoUI();
		notice.showTip((Pane) UIController.getUIController().getUIStage().getScene().getRoot(), "删除成功！");
	}

}
