package presentation.operatorUI;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;

public class UserMainUIController {
	@FXML
	private ScrollPane listPane;
	@FXML
	private Button newButton;
	@FXML
	private Button selectButton;

	//跳转新增用户窗口
	// Event Listener on Button[#newButton].onMouseClicked
	@FXML
	public void newUser(MouseEvent event) throws Exception {
		// TODO Autogenerated
		UserUIController userUIController =new UserUIController();
		userUIController.runNewUserUI();
	}

//	// Event Listener on Button[#selectButton].onMouseClicked
//	@FXML
//	public void selectUser(MouseEvent event) {
//		// TODO Autogenerated
//	}

	public void setScrollPane(VBox list) {
		// TODO Auto-generated method stub
		listPane.setStyle("-fx-border:transparent;");
		listPane.setContent(list);
	}
}
