package presentation.userUI.SaleManager;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;

public class SaleLeftSelectUIController {
	@FXML
	private Button homeButton;
	@FXML
	private Button customerButton;
	@FXML
	private Button receiptButton;
	@FXML
	private Label receiptBackground;
	@FXML
	private Label homeBackground;
	@FXML
	private Label customerBackground;

	public void init(){
		homeButton.setTooltip(new Tooltip("个人信息"));
		customerButton.setTooltip(new Tooltip("客户管理"));
		receiptButton.setTooltip(new Tooltip("单据界面"));
	}

	public void setCustomerBackground(){
		customerBackground.setVisible(true);
	}

	public void setHomeBackground(){
		homeBackground.setVisible(true);
	}

	public void setReceiptBackground(){
		receiptBackground.setVisible(true);
	}

	// Event Listener on Button[#homeButton].onMouseClicked
	@FXML
	public void toHomePane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		SaleUIController saleController = SaleUIController.getSaleUIController();
		saleController.runNewStage("homeButton");
	}
	// Event Listener on Button[#customerButton].onMouseClicked
	@FXML
	public void toCustomerPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		SaleUIController saleController = SaleUIController.getSaleUIController();
		saleController.runNewStage("customerButton");
	}
	// Event Listener on Button[#receiptButton].onMouseClicked
	@FXML
	public void toRecieptPane(MouseEvent event) throws IOException {
		// TODO Autogenerated
		SaleUIController saleController = SaleUIController.getSaleUIController();
		saleController.runNewStage("receiptButton");
	}
}
