package presentation.userUI.SaleManager;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

public class SaleReceiptSelectController {
	@FXML
	private Label purchaseForm;
	@FXML
	private Label purchaseReturnForm;
	@FXML
	private Label saleSlipForm;
	@FXML
	private Label saleReturnSlipForm;


	// Event Listener on Label[#newCashForm].onMouseClicked
	@FXML
	public void topurchaseForm(MouseEvent event) throws IOException {
		// TODO Autogenerated
		SaleUIController.getSaleUIController().setSelect("purchaseForm");
		SaleUIController.getSaleUIController().runNewStage("receiptButton");
	}
	// Event Listener on Label[#receiptForm].onMouseClicked
	@FXML
	public void topurchaseReturnForm(MouseEvent event) throws IOException {
		// TODO Autogenerated
		SaleUIController.getSaleUIController().setSelect("purchaseReturnForm");
		SaleUIController.getSaleUIController().runNewStage("receiptButton");
	}
	// Event Listener on Label[#payForm].onMouseClicked
	@FXML
	public void tosaleSlipForm(MouseEvent event) throws IOException {
		// TODO Autogenerated
		SaleUIController.getSaleUIController().setSelect("saleSlipForm");
		SaleUIController.getSaleUIController().runNewStage("receiptButton");
	}
	@FXML
	public void tosaleReturnSlipForm(MouseEvent event) throws IOException {
		// TODO Autogenerated
		SaleUIController.getSaleUIController().setSelect("saleReturnSlipForm");
		SaleUIController.getSaleUIController().runNewStage("receiptButton");
	}
}
